#!/bin/sh
#
# jawas init script
#

CONF=/usr/local/etc/jawas.conf 
. $CONF

case "$1" in
'stop')
	case "$2" in
	'prod')
		echo "Stopping Production";
		kill `cat $PROD/jawas.pid`
		;;
	*)
		echo "Stopping Development";
		kill `cat $DEV/jawas.pid`
		;;
	esac
	;;
'start')
	case "$2" in
	'prod')
		echo "Starting Production";
		export LD_LIBRARY_PATH="$PROD"
		cd $PROD && exec ./jawasd -d >jawas.log 2>&1 &
		;;
	*)
		echo "Starting Development";
		export LD_LIBRARY_PATH="$DEV"
		cd $DEV && exec ./jawasd -d >jawas.log 2>&1 &
		;;
	esac
	;;
*)
	echo "Usage: jawas [start|stop] [prod]"
	;;
esac

