# 
# jawascript makefile
#


LIBRARY = libjawascript.dylib
PROGRAM = jws

CFLAGS =  -ggdb
INCLUDES = -I../

OTHER_OBJS = ../alloc.o ../str.o ../log.o ../pages.o ../files.o

SOURCES = \
	parser.c \
	script.c

include ../rules.mk
